config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  post '/events/:id',  to: 'events#destroy'

  get '/events/index', to: 'events#index'

  get '/events/main', to: 'events#main'

  get '/events/new', to: 'events#new'

  get '/events/edit/:id', to: 'events#edit'

  get '/events/public', to: 'events#public'

  patch '/events/:id', to: 'events#update'

  post '/events', to: 'events#create'

  get '/key/show', to: 'key#show'

  get '/events/:id/destroy_photo', to: 'events#destroy_photo'

  resources :events do
    member do
      delete :destroy_photo
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'events#/events/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# frozen_string_literal: false

#class Event
class Event < ApplicationRecord
  belongs_to :user

  has_one_attached :foto

  scope :user_event, ->(user) { where(user_id: user.id) }
end

app/models/user.rb
# frozen_string_literal: false

# class User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :events

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def self.send_reminder_emails
    events = Event.where(fecha: Date.tomorrow)
    events.each do |event|
      UserMailer.reminder_email(event.user).deliver
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: false

# class Events
class EventsController < ApplicationController
  require 'csv'

  before_action :authenticate_user!

  before_action :set_event, only: [:edit, :destroy, :update]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.create(events_params)

    if @event.save
      redirect_to events_index_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @date = params[:fecha]
    @private = params[:privado]

    filter
    filer_private
  end

  def filter
    if @date
      @event = Event.user_event(current_user).where(fecha: @date).paginate(page: params[:page], per_page: 3)
      @date = ''
    else
      @event = Event.user_event(current_user).paginate(page: params[:page], per_page: 3)
    end
  end

  def filer_private
    @event = Event.user_event(current_user).where(privado: @private).paginate(page: params[:page], per_page: 3) if @private
    @private = ''
  end

  def public
    @date = params[:fecha]
    if @date
      @event = Event.where(fecha: @date, privado: false).paginate(page: params[:page], per_page: 3)
      @date = ''
    else
      @event = Event.where(privado: false).paginate(page: params[:page], per_page: 3)
    end
  end

  def edit
  end

  def update
    if @event.update(events_params)
      redirect_to events_index_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy

    redirect_to events_index_path
  end

  def destroy_photo
    @event = Event.find(params[:id])
    @event.foto.destroy
    redirect_back fallback_location: events_index_path, notice: 'succes'
  end

  def set_event
    @event = Event.find(params[:id])
  end

  private

  def events_params
    params.require(:event).permit(
      :id, :titulo, :descripcion, :fecha, :ubicacion, :latitud, :longitud, :costo, :privado, :user_id, :foto
    )
  end
end

app/controllers/key_controller.rb
class KeyController < ApplicationController
  def show
    render json: { api_key: ENV['API_KEY'] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="container">
  <%= form_with(model: @event, method: "patch", class: "my-form") do |form| %>
    <div class="mb-3">
      <%= form.label :titulo, "Titulo", class: "form-label" %>
      <%= form.text_field :titulo, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :descripcion, "Descripción", class: "form-label" %>
      <%= form.text_field :descripcion, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :fecha, "Fecha", class: "form-label" %>
      <%= form.date_field :fecha, class: "form-control" %>
    </div>

   <div data-controller="map" class="mb-3">
        <%= form.label :ubicacion, "Ubicacion", class: "form-label" %>
        <div id="map" style="width: 100%; height: 300px;"></div>
        <%= form.text_field :ubicacion, class: "form-control ubicacion", required: true %>
        <%= form.text_field :latitud, class: "form-control latitud", required: true %>
        <%= form.text_field :longitud, class: "form-control longitud", required: true %>
    </div> 

    <div class="mb-3">
      <%= form.label :costo, "Costo", class: "form-label" %>
      <%= form.number_field :costo, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.check_box :privado, class: "form-check-input" %>
        <%= form.label :privado, "Privado", class: "form-check-label" %>
        <%= form.label :foto, 'Cambiar Imagen', class: "form-label" %>
        <%= form.file_field :foto, class: "form-control-file" %>
    </div>

    <div class="text-center">
      <%= form.submit "Guardar Cambios", class: "btn btn-primary", data: { disable_with: "Creando Evento..." } %>
      <%= link_to "Regresar", events_index_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/events/index.csv.erb
<%- headers = ['Titulo', 'Descripcion', 'Fecha', 'Ubicacion', 'Ubicacion', '', 'Costo', 'Privado', 'Foto'] -%>
<%= CSV.generate_line headers %>
<%- @event.each do |event| -%>
  <%= CSV.generate_line([event.titulo, event.descripcion, event.fecha, event.ubicacion, event.costo, event.privado, event.foto]) -%>
<%- end -%>

app/views/events/index.html.erb
<div style="width: 1000px; margin-top: 100px; max-height: 700px; overflow-y: auto; margin-left: 23%;">
  <div class="d-flex flex-wrap justify-content-between">
    <% @event.each do |event| %>
    <div class="mr-3 mb-3" style="width: calc(33.33% - 1rem); max-width: calc(33.33% - 1rem);">
      <div class="card h-100" style="width: 100%; border-radius: 15px; border: 1px solid #E0E0E0; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
          <h5 class="card-title"><%= event.id %>._ <%= event.titulo %></h5>
          <%= event.foto.attached? ? 
            (image_tag event.foto) +
            (link_to 'Eliminar Foto', destroy_photo_event_path(event), class: 'delete-photo', method: :delete, data: { confirm: '¿Estás seguro de que quieres eliminar esta foto?' }) :
            ('No hay foto de este evento') %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= event.descripcion %></li>
          <li class="list-group-item"> Fecha: <%= event.fecha %></li>
          <li class="list-group-item"><%= event.ubicacion.gsub(".", "<br>").html_safe %></li>
          <li class="list-group-item"> Costo: <%= event.costo %> Privado: <%= event.privado ? 'Si' : 'No' %></li>
        </ul>
        <div class="buttons">
          <%= button_to event_path(event), method: :delete do %>
             <%= image_tag "icons/trash.svg" %>
          <% end %>
          <%= link_to 'Editar', edit_event_path(event), class: 'beditar' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/events/main.html.erb
<div class="d-flex align-items-center justify-content-center container" style="margin-top: 400px">
<h1>Sistema de Gestion de Eventos</h1>
</div>

app/views/events/new.html.erb
<div class="container">
  <%= form_with(model: @event, method: "post", class: "my-form") do |form| %>
    <div class="mb-3">
        <%= form.label :titulo, "Titulo", class: "form-label" %>
        <%= form.text_field :titulo, class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <%= form.label :descripcion, "Descripción", class: "form-label" %>
        <%= form.text_field :descripcion, class: "form-control", required: true %>
    </div>

    <div class="mb-3">
        <%= form.label :fecha, "Fecha", class: "form-label" %>
        <%= form.date_field :fecha, class: "form-control", required: true %>
    </div>

    <div data-controller="map" class="mb-3">
        <%= form.label :ubicacion, "Ubicacion", class: "form-label" %>
        <div id="map" style="width: 100%; height: 300px;"></div>
        <%= form.text_field :ubicacion, class: "form-control ubicacion", placeholder: "direccion", required: true %>
        <%= form.text_field :latitud, class: "form-control latitud", placeholder: "latitud", required: true %>
        <%= form.text_field :longitud, class: "form-control longitud", placeholder: "longitud", required: true %>
    </div>  

    <div class="mb-3">
        <%= form.label :costo, class: "form-label" %>
        <%= form.number_field :costo, class: "form-control", required: true %>
    </div>

    <div class="mb-3 ml-5">
        <%= form.check_box :privado, class: "form-check-input" %>
        <%= form.label :privado, "Privado", class: "form-check-label" %>
        <%= form.label :foto, 'Imagen', class: "form-label" %>
        <%= form.file_field :foto, class: "form-control-file" %>
    </div>

    <div class="text-center">
        <%= form.submit "Guardar Evento", class: "btn btn-primary", data: { disable_with: "Creando Evento..." } %>
        <%= link_to "Regresar", events_index_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/events/public.csv.erb
<%- headers = ['Dueño', 'Titulo', 'Descripcion', 'Fecha', 'Ubicacion', 'Ubicacion', '', 'Costo', 'Privado', 'Foto'] -%>
<%= CSV.generate_line headers %>
<%- @event.each do |event| -%>
  <%= CSV.generate_line([event.user.name, event.titulo, event.descripcion, event.fecha, event.ubicacion, event.costo, event.privado, event.foto]) -%>
<%- end -%>

app/views/events/public.html.erb
<div style="width: 1000px; margin-top: 100px; max-height: 700px; overflow-y: auto; margin-left: 23%;">
  <div class="d-flex flex-wrap justify-content-between">
    <% @event.each do |event| %>
    <div class="mr-3 mb-3" style="width: calc(33.33% - 1rem); max-width: calc(33.33% - 1rem);">
      <div class="card h-100" style="width: 100%; border-radius: 15px; border: 1px solid #E0E0E0; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <div class="card-body">
              <h5 class="card-title"> Dueño: <%= event.user.name %><%= image_tag "icons/user.svg" %></h5>
              <h5 class="card-title"> Titulo: <%= event.titulo %><%= image_tag "icons/title.svg" %></h5>
            </div>
              <%= event.foto.attached? ? (image_tag event.foto) : ('No hay foto de este evento') %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= image_tag "icons/description.svg" %> Descripción: <%= event.descripcion %></li>
          <li class="list-group-item"> <%= image_tag "icons/date.svg" %> Fecha: <%= event.fecha %></li>
          <li class="list-group-item"><%= image_tag "icons/location.svg" %> <%= event.ubicacion.gsub(".", "<br>").html_safe %></li>
          <li class="list-group-item"> Costo: <%= image_tag "icons/price.svg" %><%= event.costo %> </li>
        </ul>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_filter.html.erb
<div class="search">
    <form>
      <% if signed_in? && current_page?(events_index_path)%>
        <%= select_tag(:privado, options_for_select([['Privado', true], ['Publico', false]]), class: 'check') %>
        <%= submit_tag "Filtrar Tipo", class: "filter" %>
        <%= link_to 'Reiniciar', events_index_path, class: "filter" %>   
      <% end %>
    </form>
    <% if signed_in? && current_page?(events_public_path)%>
      <%= link_to 'Reiniciar', events_public_path, class: "filter" %>
    <% end %>
    <form>
      <% if signed_in? && (current_page?(events_index_path) || current_page?(events_public_path))%>
        <%= date_field :fecha, @date, class: 'field',required: true %>
        <%= submit_tag "Filtrar Fecha", class: "filter" %>
        <%= will_paginate @event, 
                  previous_label: '<span class="previous"> </span>', 
                  next_label: '<span class="next"> </span>', 
                  previous_disabled_class: 'disabled', 
                  next_disabled_class: @event.next_page ? nil : 'disabled', class: 'paginate'
        %>
      <% end %>
    </form>
</div> 

app/views/layouts/_navbar.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% unless signed_in? %>
          <p class="text-light">SISTEMA DE GESTION DE EVENTOS</p>
          <% else %>
            <%= link_to "Sistema de Gestion Eventos", events_main_path, class: "btn btn-dark text-light" %>
          <% end %>
        <li class="nav-item">
          <% if signed_in? && current_page?(events_main_path) || current_page?(root_path)%>
            <%= link_to "Iniciar", events_index_path , class: "nav-link active"%>
          <% end %>
        </li>
        <li class="nav-item">
          <% if signed_in? && current_page?(events_index_path)%>
            <%= link_to "Añadir nuevo evento", events_new_path , class: "nav-link active"%>
            <% else %>
              <% link_to destroy_user_session_path, data:{turbo_method: :delete} %>
          <% end %>
        </li>
          <% if signed_in? && current_page?(events_index_path)%>
            <li class="nav-item">
              <%= link_to "Eventos Publicos", events_public_path , class: "nav-link active"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Descargar mis Eventos', events_index_path(format: :csv), class: "nav-link active" %>
            </li>
          <% end %>
        <% if signed_in? && current_page?(events_public_path)%>
          <li class="nav-item">
              <%= link_to "Mis Eventos", events_index_path , class: "nav-link active"%>
          </li>
            <li class="nav-item">
              <%= link_to 'Descargar Eventos Publicos', events_public_path(format: :csv), class: "nav-link active" %>
          </li>
        <% end %>
      </ul>

      <p class="text-light"><%= current_user.name if current_user%></p>
      
      <div>
        <% if signed_in? %>
          <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, data:{turbo_method: :delete},class: "btn btn-dark" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administrador de Eventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'Control-Geocoder' %>
    <%= stylesheet_link_tag 'login' %>
    <%= stylesheet_link_tag 'index' %>
    <%= stylesheet_link_tag 'filter' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/filter' %>
    
    <%= yield %>

  </body>

  <%= javascript_include_tag "leaflet" %>
  <%= javascript_include_tag "Control-Geocoder" %>
  
</html>